name: Build iOS VPN Demo UI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios-demo:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Build iOS App
        run: |
          xcodebuild \
            -project TestApp.xcodeproj \
            -scheme TestApp \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_VERSION=5.0

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-Release
          path: build/Build/Products/Release-iphoneos/TestApp.app
