name: Build and Test WorxVPN Demo App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you use CocoaPods, uncomment these lines
      # - name: Install CocoaPods dependencies
      #   run: |
      #     brew install cocoapods || true
      #     pod install || true

      - name: Build App
        run: |
          xcodebuild \
            -project TestApp.xcodeproj \
            -scheme TestApp \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            build

      - name: Run Tests (if configured)
        run: |
          xcodebuild \
            -project TestApp.xcodeproj \
            -scheme TestApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            test

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-Release
          path: build/Release-iphonesimulator/TestApp.app
          if-no-files-found: warn