name: Build and Test WorxVPN Phase 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect scheme
        id: detect_scheme
        run: |
          SCHEME=$(xcodebuild -list -project "WorxVPN_Phase1_CompleteFinal/WorxVPN_TestApp.xcodeproj" | awk '/Schemes:/ {getline; print $1}')
          echo "SCHEME=$SCHEME" >> $GITHUB_ENV

      - name: Build App
        run: |
          xcodebuild \
            -project "WorxVPN_Phase1_CompleteFinal/WorxVPN_TestApp.xcodeproj" \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            build

      - name: Run Tests
        run: |
          xcodebuild \
            -project "WorxVPN_Phase1_CompleteFinal/WorxVPN_TestApp.xcodeproj" \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            test

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: Phase1-iOS-App
          path: WorxVPN_Phase1_CompleteFinal/build/Release-iphonesimulator/*.app
          if-no-files-found: warn