name: Build and Test WorxVPN Phase 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Xcode project file
        id: detect_proj
        run: |
          PROJ=$(ls *.xcodeproj | head -n 1)
          echo "project=$PROJ" >> $GITHUB_OUTPUT

      - name: Detect Scheme
        id: detect_scheme
        run: |
          SCHEME=$(xcodebuild -list -project ${{ steps.detect_proj.outputs.project }} | awk '/Schemes:/ {getline; print $1}')
          echo "scheme=$SCHEME" >> $GITHUB_OUTPUT

      - name: Build App
        run: |
          xcodebuild \
            -project ${{ steps.detect_proj.outputs.project }} \
            -scheme ${{ steps.detect_scheme.outputs.scheme }} \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            build

      - name: Run Tests (if configured)
        run: |
          xcodebuild \
            -project ${{ steps.detect_proj.outputs.project }} \
            -scheme ${{ steps.detect_scheme.outputs.scheme }} \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            test

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: Phase1-iOS-App
          path: build/Release-iphonesimulator/*.app
          if-no-files-found: warn